"""v1

Revision ID: 31cfcddc9086
Revises: 
Create Date: 2021-02-17 15:26:11.566141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cfcddc9086'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coursename', sa.String(length=64), nullable=True),
    sa.Column('courseholes', sa.Integer(), nullable=True),
    sa.Column('courselocation', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_coursename'), 'course', ['coursename'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('hole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holenum', sa.Integer(), nullable=True),
    sa.Column('holepar', sa.Integer(), nullable=True),
    sa.Column('holelength', sa.Integer(), nullable=True),
    sa.Column('holecourse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holecourse_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holenum', 'holecourse_id')
    )
    op.create_index(op.f('ix_hole_holenum'), 'hole', ['holenum'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hole_holenum'), table_name='hole')
    op.drop_table('hole')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_course_coursename'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
