"""v1.2

Revision ID: a57886142350
Revises: 31cfcddc9086
Create Date: 2021-02-17 17:02:04.005384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57886142350'
down_revision = '31cfcddc9086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_hole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holenum', sa.Integer(), nullable=True),
    sa.Column('holepar', sa.Integer(), nullable=True),
    sa.Column('holelength', sa.Integer(), nullable=True),
    sa.Column('holecourse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holecourse_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holenum', 'holecourse_id')
    )
    op.create_index(op.f('ix_course_hole_holenum'), 'course_hole', ['holenum'], unique=False)
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rounddate', sa.DateTime(), nullable=True),
    sa.Column('roundweather', sa.String(length=16), nullable=True),
    sa.Column('rounduser_id', sa.Integer(), nullable=True),
    sa.Column('roundcourse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roundcourse_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['rounduser_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_hole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hole', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('ob', sa.Boolean(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hole', 'round_id')
    )
    op.drop_index('ix_hole_holenum', table_name='hole')
    op.drop_table('hole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hole',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('holenum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('holepar', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('holelength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('holecourse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['holecourse_id'], ['course.id'], name='hole_holecourse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hole_pkey'),
    sa.UniqueConstraint('holenum', 'holecourse_id', name='hole_holenum_holecourse_id_key')
    )
    op.create_index('ix_hole_holenum', 'hole', ['holenum'], unique=False)
    op.drop_table('round_hole')
    op.drop_table('round')
    op.drop_index(op.f('ix_course_hole_holenum'), table_name='course_hole')
    op.drop_table('course_hole')
    # ### end Alembic commands ###
